from .auth_routes import auth_routes
from .user_routes import user_routes
from .wishlists_routes import wishlists_routes
from .favorites_routes import favorites_routes
from .paystub_routes import paystub_routes
from .category_routes import category_routes
from .product_routes import product_routes
from .orders_routes import orders_routes
from .review_routes import review_routes
from .complaint_routes import complaint_routes
